from __future__ import annotations

# This package is the single source of truth (SSOT) for cross-cutting contracts.
# The definitions were split into thematic submodules (see _common, _runs, etc.)
# for maintainability; this module re-exports every public name so that the
# historical import surface ("from packages.core.contracts import X") is unchanged.
#
# Re-exports use the explicit "name as name" form so static checkers (ruff F401)
# recognise them as intentional public re-exports without an __all__.

# Re-exported standard/third-party symbols (preserved for backward-compatible imports).
from datetime import datetime as datetime, timedelta as timedelta, timezone as timezone
from decimal import Decimal as Decimal
from enum import Enum as Enum
from typing import (
    Annotated as Annotated,
    Any as Any,
    Generic as Generic,
    Literal as Literal,
    TypeVar as TypeVar,
)
from uuid import uuid4 as uuid4

from pydantic import (
    BaseModel as BaseModel,
    ConfigDict as ConfigDict,
    Field as Field,
    JsonValue as JsonValue,
    model_validator as model_validator,
)


from packages.core.contracts._common import (
    T as T,
    utcnow as utcnow,
    ContractModel as ContractModel,
    ErrorCode as ErrorCode,
    WarningCode as WarningCode,
    DegradationCode as DegradationCode,
    JobStatus as JobStatus,
    RunStatus as RunStatus,
    NodeStatus as NodeStatus,
    ProviderStatus as ProviderStatus,
    JobType as JobType,
    ArtifactKind as ArtifactKind,
    UploadSessionStatus as UploadSessionStatus,
    UploadStatus as UploadStatus,
    UploadKind as UploadKind,
    UserRole as UserRole,
    Money as Money,
    zero_money as zero_money,
    EntityMeta as EntityMeta,
    BaseListQuery as BaseListQuery,
    OkResponse as OkResponse,
    PageResponse as PageResponse,
    SignedUrlResponse as SignedUrlResponse,
    EventStreamTokenResponse as EventStreamTokenResponse,
    RunEvent as RunEvent,
    NodeError as NodeError,
    DegradationNotice as DegradationNotice,
    ErrorEnvelope as ErrorEnvelope,
    ArtifactRef as ArtifactRef,
    MediaInfo as MediaInfo,
    Artifact as Artifact,
    ProviderError as ProviderError,
)

from packages.core.contracts._workflow import (
    UsageMeterRecord as UsageMeterRecord,
    ProviderInvocation as ProviderInvocation,
    RetryPolicy as RetryPolicy,
    ResumePolicy as ResumePolicy,
    WorkflowEdge as WorkflowEdge,
    NodeSpec as NodeSpec,
    WorkflowTemplate as WorkflowTemplate,
)

from packages.core.contracts._media import (
    MediaAssetRecord as MediaAssetRecord,
    SelectionMedium as SelectionMedium,
    SelectionLedgerEntry as SelectionLedgerEntry,
    MaterialUsageRankingItem as MaterialUsageRankingItem,
    MaterialUsageRankingReport as MaterialUsageRankingReport,
    MediaAssetQuery as MediaAssetQuery,
    CreateMediaAssetFromUploadRequest as CreateMediaAssetFromUploadRequest,
    MediaAssetCard as MediaAssetCard,
    MediaAssetDetail as MediaAssetDetail,
    BatchStabilizeMediaAssetsRequest as BatchStabilizeMediaAssetsRequest,
    MediaAssetProcessingResult as MediaAssetProcessingResult,
    BatchMediaProcessResponse as BatchMediaProcessResponse,
    TimelineSegment as TimelineSegment,
    TrimAnnotationRequest as TrimAnnotationRequest,
    TrimAnnotationResponse as TrimAnnotationResponse,
    MediaAssetReplaceSourceRequest as MediaAssetReplaceSourceRequest,
    MediaAssetReplaceResponse as MediaAssetReplaceResponse,
    AutoMatchReplaceRequest as AutoMatchReplaceRequest,
    AutoMatchReplaceResult as AutoMatchReplaceResult,
    AutoMatchReplaceResponse as AutoMatchReplaceResponse,
    AnnotationPatch as AnnotationPatch,
    PatchAnnotationRequest as PatchAnnotationRequest,
    RerunAnnotationRequest as RerunAnnotationRequest,
    AnnotationRunResponse as AnnotationRunResponse,
    AnnotationEditorVm as AnnotationEditorVm,
    VoiceProfile as VoiceProfile,
    VoiceQuery as VoiceQuery,
    CloneVoiceRequest as CloneVoiceRequest,
    DesignVoiceRequest as DesignVoiceRequest,
    VoicePreviewRequest as VoicePreviewRequest,
    VoicePreviewResponse as VoicePreviewResponse,
    PatchVoiceRequest as PatchVoiceRequest,
)

from packages.core.contracts._prompts import (
    PromptSchemaRef as PromptSchemaRef,
    PromptTemplate as PromptTemplate,
    PromptVersion as PromptVersion,
    PromptBinding as PromptBinding,
    PromptInvocation as PromptInvocation,
    PromptTemplateQuery as PromptTemplateQuery,
    PromptTemplateView as PromptTemplateView,
    PromptVersionView as PromptVersionView,
    PromptBindingQuery as PromptBindingQuery,
    PromptBindingView as PromptBindingView,
    CreatePromptTemplateRequest as CreatePromptTemplateRequest,
    CreatePromptVersionRequest as CreatePromptVersionRequest,
    ApprovePromptVersionRequest as ApprovePromptVersionRequest,
    PublishPromptVersionRequest as PublishPromptVersionRequest,
    RollbackPromptRequest as RollbackPromptRequest,
    CreatePromptBindingRequest as CreatePromptBindingRequest,
    PatchPromptBindingRequest as PatchPromptBindingRequest,
    PromptExperimentScope as PromptExperimentScope,
    PromptExperiment as PromptExperiment,
    PromptExperimentQuery as PromptExperimentQuery,
    CreatePromptExperimentRequest as CreatePromptExperimentRequest,
    PatchPromptExperimentRequest as PatchPromptExperimentRequest,
)

from packages.core.contracts._providers import (
    ProviderOptionsSchemaRef as ProviderOptionsSchemaRef,
    ProviderCapability as ProviderCapability,
    ProviderProfile as ProviderProfile,
    ProviderProfileQuery as ProviderProfileQuery,
    CreateProviderProfileRequest as CreateProviderProfileRequest,
    PatchProviderProfileRequest as PatchProviderProfileRequest,
    TestProviderProfileRequest as TestProviderProfileRequest,
    ProviderHealthCheckResponse as ProviderHealthCheckResponse,
    ProviderPriceCatalog as ProviderPriceCatalog,
    ProviderPriceItem as ProviderPriceItem,
    PriceCatalogQuery as PriceCatalogQuery,
    UpsertPriceCatalogRequest as UpsertPriceCatalogRequest,
    ProviderUsageQuery as ProviderUsageQuery,
    ProviderUsageReport as ProviderUsageReport,
    ProviderUsageMetricsItem as ProviderUsageMetricsItem,
    ProviderUsageMetricsReport as ProviderUsageMetricsReport,
    CostEstimateLine as CostEstimateLine,
    DigitalHumanVideoCostEstimateResponse as DigitalHumanVideoCostEstimateResponse,
    GovernedActionRequest as GovernedActionRequest,
    ProviderBalanceQuery as ProviderBalanceQuery,
    ProviderBalanceItem as ProviderBalanceItem,
    ProviderBalanceReport as ProviderBalanceReport,
    RefreshProviderBalancesRequest as RefreshProviderBalancesRequest,
    ProviderBalanceSnapshot as ProviderBalanceSnapshot,
    ReconcileBillingRequest as ReconcileBillingRequest,
    ReconcileBillingResponse as ReconcileBillingResponse,
)

from packages.core.contracts._creative import (
    ScriptVersion as ScriptVersion,
    VideoVersion as VideoVersion,
    PublishRecord as PublishRecord,
    PerformanceObservation as PerformanceObservation,
    PerformanceMetricView as PerformanceMetricView,
    CreativeFeatureVector as CreativeFeatureVector,
    CaseMemoryScope as CaseMemoryScope,
    CaseMemory as CaseMemory,
    MemoryProposal as MemoryProposal,
    ReflectionRun as ReflectionRun,
    CaseAgentSourceBinding as CaseAgentSourceBinding,
    CreativeBrief as CreativeBrief,
    ScriptDraft as ScriptDraft,
    CaseAgentRun as CaseAgentRun,
    CaseAgentRunQuery as CaseAgentRunQuery,
    CreateSourceBindingRequest as CreateSourceBindingRequest,
    ImportCaseSourceRequest as ImportCaseSourceRequest,
    StartCaseAgentRunRequest as StartCaseAgentRunRequest,
    CaseAgentRunDetail as CaseAgentRunDetail,
    ScriptDraftQuery as ScriptDraftQuery,
    AdoptScriptDraftRequest as AdoptScriptDraftRequest,
    MemoryProposalQuery as MemoryProposalQuery,
    ApproveMemoryRequest as ApproveMemoryRequest,
    RejectMemoryRequest as RejectMemoryRequest,
    CaseKnowledgeResponse as CaseKnowledgeResponse,
    CasePerformanceQuery as CasePerformanceQuery,
    CasePerformanceResponse as CasePerformanceResponse,
    StartReflectionRunRequest as StartReflectionRunRequest,
    GenerateScriptWithMemoryRequest as GenerateScriptWithMemoryRequest,
    ReferenceExtractRequest as ReferenceExtractRequest,
    ReferenceExtractResult as ReferenceExtractResult,
    PerformanceAttributionResponse as PerformanceAttributionResponse,
    CreativePattern as CreativePattern,
    CaseInsightCard as CaseInsightCard,
    MetricsImportRequest as MetricsImportRequest,
)

from packages.core.contracts._publishing import (
    FinishedVideo as FinishedVideo,
    FinishedVideoQuery as FinishedVideoQuery,
    FinishedVideoDetail as FinishedVideoDetail,
    PublishDefaults as PublishDefaults,
    PublishPackage as PublishPackage,
    CreateEditorHandoffRequest as CreateEditorHandoffRequest,
    EditorHandoffPackageArtifact as EditorHandoffPackageArtifact,
    CreateJianyingDraftRequest as CreateJianyingDraftRequest,
    JianyingDraftPackageArtifact as JianyingDraftPackageArtifact,
    PublishPackageQuery as PublishPackageQuery,
    CreatePublishPackageRequest as CreatePublishPackageRequest,
    PatchPublishPackageRequest as PatchPublishPackageRequest,
    DeletePublishResourceRequest as DeletePublishResourceRequest,
    PublishBatchStatus as PublishBatchStatus,
    PublishItemStatus as PublishItemStatus,
    PublishAttemptStatus as PublishAttemptStatus,
    PublishBatchItemVm as PublishBatchItemVm,
    PublishBatchVm as PublishBatchVm,
    PublishBatchQuery as PublishBatchQuery,
    CreatePublishBatchRequest as CreatePublishBatchRequest,
    SubmitPublishBatchRequest as SubmitPublishBatchRequest,
    PatchPublishItemRequest as PatchPublishItemRequest,
    PublishAttempt as PublishAttempt,
    PublishAttemptDetail as PublishAttemptDetail,
)

from packages.core.contracts._runs import (
    VoiceOptions as VoiceOptions,
    PortraitOptions as PortraitOptions,
    BrollOptions as BrollOptions,
    LipSyncOptions as LipSyncOptions,
    SubtitleOptions as SubtitleOptions,
    BgmOptions as BgmOptions,
    CoverOptions as CoverOptions,
    OutputOptions as OutputOptions,
    StrictnessOptions as StrictnessOptions,
    DigitalHumanVideoRequest as DigitalHumanVideoRequest,
    CaseAgentRunRequest as CaseAgentRunRequest,
    PublishBatchRequest as PublishBatchRequest,
    AnnotationBatchRequest as AnnotationBatchRequest,
    JobRequest as JobRequest,
    Job as Job,
    WorkflowRun as WorkflowRun,
    NodeRun as NodeRun,
    ValidatedProductionSpec as ValidatedProductionSpec,
    AuthUser as AuthUser,
    SessionInfo as SessionInfo,
    LoginRequest as LoginRequest,
    RegisterRequest as RegisterRequest,
    AuthResponse as AuthResponse,
    ChangePasswordRequest as ChangePasswordRequest,
    UserListQuery as UserListQuery,
    AdminCreateUserRequest as AdminCreateUserRequest,
    AdminUpdateUserRequest as AdminUpdateUserRequest,
    RegistrationCodeQuery as RegistrationCodeQuery,
    RegistrationCodePreview as RegistrationCodePreview,
    CreatedRegistrationCode as CreatedRegistrationCode,
    CreateRegistrationCodeRequest as CreateRegistrationCodeRequest,
    UpdateRegistrationCodeRequest as UpdateRegistrationCodeRequest,
    UpdateMeRequest as UpdateMeRequest,
    PrepareUploadRequest as PrepareUploadRequest,
    UploadSession as UploadSession,
    CompleteUploadRequest as CompleteUploadRequest,
    CompleteUploadResponse as CompleteUploadResponse,
    SecretQuery as SecretQuery,
    CreateSecretRequest as CreateSecretRequest,
    RotateSecretRequest as RotateSecretRequest,
    DisableSecretRequest as DisableSecretRequest,
    SecretStatus as SecretStatus,
    SecretRecord as SecretRecord,
    SecretPreview as SecretPreview,
    CaseListQuery as CaseListQuery,
    CreateCaseRequest as CreateCaseRequest,
    PatchCaseRequest as PatchCaseRequest,
    DeleteCaseRequest as DeleteCaseRequest,
    CaseListItem as CaseListItem,
    CaseDetail as CaseDetail,
    CreateDigitalHumanVideoJobRequest as CreateDigitalHumanVideoJobRequest,
    CreateRunRequest as CreateRunRequest,
    CancelRunRequest as CancelRunRequest,
    RetryRunRequest as RetryRunRequest,
    ResumeRunRequest as ResumeRunRequest,
    WorkflowRunResponse as WorkflowRunResponse,
    RetryRunResponse as RetryRunResponse,
    ResumeRunResponse as ResumeRunResponse,
    CreateJobResponse as CreateJobResponse,
    JobDetailResponse as JobDetailResponse,
    RunDetailResponse as RunDetailResponse,
    RunCard as RunCard,
    RunActionResponse as RunActionResponse,
    RunPublicReportArtifact as RunPublicReportArtifact,
    RunDebugReportArtifact as RunDebugReportArtifact,
    RunReportResponse as RunReportResponse,
    RunArtifactsResponse as RunArtifactsResponse,
    RunEventsQuery as RunEventsQuery,
)

from packages.core.contracts._ops import (
    OpsDashboardQuery as OpsDashboardQuery,
    CostRollup as CostRollup,
    CostRollupQuery as CostRollupQuery,
    YieldFunnelEvent as YieldFunnelEvent,
    YieldFunnelQuery as YieldFunnelQuery,
    YieldFunnelResponse as YieldFunnelResponse,
    Budget as Budget,
    BudgetQuery as BudgetQuery,
    UpsertBudgetRequest as UpsertBudgetRequest,
    PatchBudgetRequest as PatchBudgetRequest,
    OpsAlertEvent as OpsAlertEvent,
    AcknowledgeAlertRequest as AcknowledgeAlertRequest,
    ResolveAlertRequest as ResolveAlertRequest,
    ProductionQualityCheck as ProductionQualityCheck,
    CreateQualityCheckRequest as CreateQualityCheckRequest,
    ApprovalRequest as ApprovalRequest,
    ApprovalDecisionRequest as ApprovalDecisionRequest,
    AuditEvent as AuditEvent,
    AuditEventQuery as AuditEventQuery,
    OpsDashboardVm as OpsDashboardVm,
    ImportBatchStatus as ImportBatchStatus,
    CreateImportBatchRequest as CreateImportBatchRequest,
    ImportRowResult as ImportRowResult,
    ImportBatchReport as ImportBatchReport,
    OutboxEvent as OutboxEvent,
    signed_local_url as signed_local_url,
)
